# Generated by Django 5.1.3 on 2024-12-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_saled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_saled',
            new_name='is_sale',
        ),
    ]
